### ISSUE TITLE
Can't run jrnl anymore

### ISSUE THREAD

**Issue by velasco** [jrnl-org/jrnl#1058]
Hi,

I wanted to jrnl today, but I got an error message. I re-installed jrnl without success. Can you help?

The error states:
``` 
Welcome to jrnl v2.4.5.

It looks like you've been using an older version of jrnl until now. That's
okay - jrnl will now upgrade your configuration and journal files. Afterwards
you can enjoy all of the great new features that come with jrnl 2:

- Support for storing your journal in multiple files
- Faster reading and writing for large journals
- New encryption back-end that makes installing jrnl much easier
- Tons of bug fixes

Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
If you choose to proceed, you will not be able to use your journals with
older versions of jrnl anymore.

Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 349, in run
    config = install.load_or_install_jrnl()
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/install.py", line 103, in load_or_install_jrnl
    upgrade.upgrade_jrnl(config_path)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/upgrade.py", line 71, in upgrade_jrnl
    if os.path.exists(os.path.expanduser(path)):
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/bin/../lib/python3.8/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not bool
```

**Comment by wren** [comment]
Hi! Thanks for the issue, and sorry you're having trouble with jrnl.

Do you happen to know what version of jrnl you were using before?

 Also, can you run with `--debug` and paste the output?

As a complete guess, can you please double-check that there isn't already a file at `~/.config/jrnl`?

**Comment by velasco** [comment]
Hi wren, thanks for getting back to me. In fact, there hasn't bin a config file, but I produced one, now. It still fails. I'm afraid I don't recall the version. I installed it about a year ago.

The debug output reads
```DEBUG    jrnl.install Reading configuration from file /Users/francisco/.config/jrnl/jrnl.yaml
DEBUG    jrnl.cli     Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': True, 'highlight': True, 'indent_character': '|', 'journals': {'default': '~\\Documents\\jrnl\\journal.txt'}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.4.5'}"
DEBUG    jrnl.cli     Using journal "default"
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 387, in run
    journal = open_journal(journal_name, config)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 405, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/EncryptedJournal.py", line 46, in open
    os.makedirs(dirname)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/bin/../lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by micahellison** [comment]
Hi there, it looks like your default journal path in your config file is `'~\\Documents\\jrnl\\journal.txt'` while it should probably be: `~/Documents/jrnl/journal.txt`

I think that's the cause of this "no such file or directory" error.

**Comment by velasco** [comment]
Thank you, this solved it.

> Hi there, it looks like your default journal path in your config file is `'~\\Documents\\jrnl\\journal.txt'` while it should probably be: `~/Documents/jrnl/journal.txt`
> 
> I think that's the cause of this "no such file or directory" error.
