### ISSUE TITLE
Uncaught exception when encrypting folder journal

### ISSUE THREAD

**Issue by StefanoChiodino** [jrnl-org/jrnl#1243]
### Environment
  - `jrnl --diagnostic` output:
```
jrnl: v2.8.1
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
OS: Linux 5.4.0-72-generic
```
  - Install method: pipx

### Current Behavior

Throws when trying to encrypt a folder

```
➜  ~ jrnl --encrypt
Enter password for new journal: 
Enter password again: 
Do you want to store the password in your keychain? [Y/n] 
Traceback (most recent call last):
  File "/home/stefano/.local/bin/jrnl", line 8, in <module>
    sys.exit(cli())
  File "/home/stefano/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 35, in cli
    return run(args)
  File "/home/stefano/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 55, in run
    return args.postconfig_cmd(
  File "/home/stefano/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/commands.py", line 74, in postconfig_encrypt
    new_journal.write(args.filename)
  File "/home/stefano/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/Journal.py", line 98, in write
    self._store(filename, text)
  File "/home/stefano/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/EncryptedJournal.py", line 118, in _store
    with open(filename, "wb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/stefano/.local/share/jrnl/journal/'
```

### Expected Behavior

encrypts each file
### Repro Steps

Configure journal to use directory as per documentation: change the path to be a directory. Jrnl seems to pick this up and stored entries under year/month/day.txt format.
Encrypt with `jrnl --encrypt` and follow steps.

### Other Information

I understand the implications of thousands of files to decrypt to run a search may not be feasible. In that case, I think you could just add a better error message and/or documentation around this.

Cheers

**Comment by micahellison** [comment]
Hi there, thanks for filing this issue. We are planning to fix this, but you're absolutely right that a better error message would be a great stopgap!

**Comment by wren** [comment]
cc:  #1103
