### ISSUE TITLE
No tags on Windows

### ISSUE THREAD

**Issue by SteveDunn** [jrnl-org/jrnl#1405]
### Environment
  - `jrnl --diagnostic` output: 
 ```python
jrnl: v2.8.3
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
OS: Windows 10
```
  - Install method: installed latest python, installed latest pipx, installed via pipx

### Repro Steps
When I do the following, I get:

```python
$ jrnl --debug test tag @todo                                                                                                                                                               powershell   100  12:44:14 
DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, export=False, tags=False, short=False, config_override=[], text=['test', 'tag'])
DEBUG    root         Reading configuration from file C:\Users\sdunn\.config\jrnl\jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': 'C:\\Users\\sdunn\\Documents\\jrnl\\journal.txt'}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.8.3'}"
DEBUG    root         Using journal name: default
DEBUG    root         opened PlainJournal with 16 entries
DEBUG    root         Write mode: starting
DEBUG    root         Write mode: cli text detected: ['test', 'tag']
DEBUG    root         Write mode: appending raw text to journal "default": test tag
[Entry added to default journal]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sdunn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\sdunn\.local\bin\jrnl.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\sdunn\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\cli.py", line 34, in cli
    return run(args)
  File "C:\Users\sdunn\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 71, in run
    write_mode(**kwargs)
  File "C:\Users\sdunn\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 151, in write_mode
    logging.debug("Write mode: completed journal.write()", args.journal_name, raw)
Message: 'Write mode: completed journal.write()'
Arguments: ('default', 'test tag')
```

Then, when I do list the tags, I don't see any: `jnrl --tags` => `[No tags found in journal.]`

**Comment by micahellison** [comment]
Hi there, this is a PowerShell issue - the @ character is a special character in it. Here's the documentation on how to deal with this:
> Most shells contain a certain number of reserved characters, such as # and *. These characters, as well as unbalanced single or double quotation marks, parentheses, and others, likely will cause problems. Although reserved characters can be escaped using \, this is not ideal for long-form writing. The solution: first enter jrnl and hit return. You can then enter the text of your journal entry. Alternatively, you can use an external editor.
