### ISSUE TITLE
Read-only file system: '/Usersrs'

### ISSUE THREAD

**Issue by danielgruber99** [jrnl-org/jrnl#1573]
### Diagnostic output

jrnl: v3.1
Python: 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
OS: Darwin 21.6.0

### Current Behavior

By running the command 'jrnl' an error occurs with folling message: "OSError [Errno 30] Read-only file system: '/Usersrs'"

### Expected Behavior

The command should me let write any notes.

### Repro Steps

Only running 'jrnl'. Also 'jrnl yesterday:' or similar commands produces the same error.

### Debug output

<details><summary>Click for debug output...</summary>

```
DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False, config_override=[], config_file_path='', text=[])
DEBUG    root         Reading configuration from file /Users/q465528/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': '/Usersrs/q465528/MyJournal'}, 'linewrap': 79, 'tagsymbols': '#@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v3.1'}"
DEBUG    root         Using journal name: default
  File "/usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/cli.py", line 39, in cli
    status_code = run(args)
  File "/usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/jrnl.py", line 60, in run
    journal = open_journal(args.journal_name, config)
  File "/usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/Journal.py", line 466, in open_journal
    return PlainJournal(journal_name, **config).open()
  File "/usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/Journal.py", line 87, in open
    os.makedirs(dirname)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/cli.py: │
│ 39 in cli                                                                    │
│                                                                              │
│   38 │   │                                                                   │
│ ❱ 39 │   │   status_code = run(args)                                         │
│   40                                                                         │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/jrnl.py │
│ :60 in run                                                                   │
│                                                                              │
│    59 │   # Get the journal we're going to be working with                   │
│ ❱  60 │   journal = open_journal(args.journal_name, config)                  │
│    61                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/Journal │
│ .py:466 in open_journal                                                      │
│                                                                              │
│   465 │   │   │   return FolderJournal.Folder(journal_name, **config).open() │
│ ❱ 466 │   │   return PlainJournal(journal_name, **config).open()             │
│   467                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.1/libexec/lib/python3.10/site-packages/jrnl/Journal │
│ .py:87 in open                                                               │
│                                                                              │
│    86 │   │   │   if not os.path.isdir(dirname):                             │
│ ❱  87 │   │   │   │   os.makedirs(dirname)                                   │
│    88 │   │   │   │   print_msg(                                             │
│                                                                              │
│ /usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/ │
│ 3.10/lib/python3.10/os.py:215 in makedirs                                    │
│                                                                              │
│    214 │   │   try:                                                          │
│ ❱  215 │   │   │   makedirs(head, exist_ok=exist_ok)                         │
│    216 │   │   except FileExistsError:                                       │
│                                                                              │
│ /usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/ │
│ 3.10/lib/python3.10/os.py:225 in makedirs                                    │
│                                                                              │
│    224 │   try:                                                              │
│ ❱  225 │   │   mkdir(name, mode)                                             │
│    226 │   except OSError:                                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 30] Read-only file system: '/Usersrs'
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  OSError                                             ┃
┃  [Errno 30] Read-only file system: '/Usersrs'        ┃
┃                                                      ┃
┃  This is probably a bug. Please file an issue at:    ┃
┃  https://github.com/jrnl-org/jrnl/issues/new/choose  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

</details>

**Comment by wren** [comment]
Hi, @danielgruber99! Thanks for filing an issue.

It looks like your config has a typo. The file for your default journal is set to `/Usersrs/q465528/MyJournal`. If you update the start of the path to `/Users`, then you should be good to go. Macs don't have a `/Usersrs` directory by default, and `/` is read-only by default, so `jrnl` is getting an error when attempting to create the directory for you.

If you're still having problems after that, please update this thread, and we can look into it some more.
