### ISSUE TITLE
does not accept non ascii characters

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#295]
I started a journal in French, with accented letters, directly from the command line and when I tried to validate the entry (ctrl-d) I got the following message:

Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.6_2/libexec/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.6', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.6_2/lib/python2.7/site-packages/jrnl/cli.py", line 199, in run
    raw = " ".join(args.text).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

Same result with any non ascii character.

**Comment by teranex** [comment]
I just encountered this issue with jrnl 1.9.8 (installed through pip). After writing an entry in Vim (which is configured to use utf-8 by default) with an é in the text jrnl though the error is slightly different:

```
$ jrnl -n1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python3.4/dist-packages/jrnl/cli.py", line 241, in run
    print(util.py2encode(journal.pprint()))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 837: ordinal not in range(128)
```

**Comment by heitorsilva** [comment]
And I got a 'utf8' error: #391
