### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Th0rleif** [jrnl-org/jrnl#439]
Hello,
After a long time (circa 1 year) without going into my journal, I want to decrypt it. But unfortunately it fails and results in:

```
Traceback (most recent call last):
  File "/usr/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/lib/python3.5/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/lib/python3.5/site-packages/jrnl/util.py", line 39, in get_password
    result = validator(password)
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 98, in validate_password
    return self._decrypt(journal_encrypted)
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 69, in _decrypt
    return plain.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 1: invalid start byte
```

I don't know what does happen, but please can you fix it or tell me how to fix it?

I am running Python 3.5.2. 

regards,

**Comment by jpalmieri** [comment]
I get this same exact error. It started after I was offerred to store my password in the keychain, to which I replied 'Y'. It has given me this error since.

**Comment by jpalmieri** [comment]
I was able to fix this by manually changing the value for `encrypt` from `false` to `true` in my `~/.jrnl_config`. Then, I ran `jrnl --decrypt` and it works as normal again. It must have missed setting that flag somehow.

**Comment by neo1691** [comment]
I am getting the same error. Using OSX Sierra. Can somebody help me out getting to the bottom of the problem? 

Here is the traceback that I see.

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 108, in open
    journal = f.read()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/codecs.py", line 674, in read
    return self.reader.read(size)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/codecs.py", line 480, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 1: invalid start byte
```

Using python2 here. `python3` is also installed on my Mac but `jrnl` is using `python2`.

**Comment by wren** [comment]
Does anyone here have a chance to try v2.0 and see if this issue is still occurring?
