### ISSUE TITLE
Troubles with Unicode 

### ISSUE THREAD

**Issue by dkostenko** [jrnl-org/jrnl#454]
Thank you for your project!

There are some troubles with Unicode symbols. For instance, Russian text looks like "Ð²ÑÐ¾ÑÐ¾Ðµ ÑÐ¾Ð¾Ð±ÑÐµÐ½" in view mode.

**Comment by ocean314** [comment]
Hello. Have you resolved it?

**Comment by epogrebnyak** [comment]
`jrnl` fails on first run with following error. I'm on Windows and paths contain non-latin characters.

```
> jrnl

Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\jrnl.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\jrnl\cli.py", line 146, in run
    config = install.load_or_install_jrnl()
  File "d:\anaconda3\lib\site-packages\jrnl\install.py", line 91, in load_or_install_jrnl
    upgrade.upgrade_jrnl_if_necessary(config_path)
  File "d:\anaconda3\lib\site-packages\jrnl\upgrade.py", line 23, in upgrade_jrnl_if_necessary
    config_file = f.read()
  File "d:\anaconda3\lib\codecs.py", line 701, in read
    return self.reader.read(size)
  File "d:\anaconda3\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 135: invalid continuation byte
```

**Comment by wren** [comment]
Hi, can you please install the latest (v2.1.1) and report back if this problem still occurs? We don't see it, but aren't sure if we just don't know how to repro. 

Thank you!
