### ISSUE TITLE
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")

### ISSUE THREAD

**Issue by aaron-goshine** [jrnl-org/jrnl#472]
```bash
⦿ [\~]--❯ jrnl -n 2
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 95, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 46, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 38, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")
```

**Comment by aaron-goshine** [comment]
@maebert  please have a look at that and let me know what you think.
this jrnl file was created on a different machine.
Why is it trying to read my keychain.
My keychain will varies from machine,  seen I store my jrnl files in the cloud accessible by multiple machine, even different OS for instance Linux or Mac.

**Comment by maebert** [comment]
You're on OS X I assume? Could you try `pip install -U keyring` on the affected machine and let me know if that fixes things?

**Comment by cecep2** [comment]
I have the same error, but I didn't move to a different machine. OS X Sierra, running jrnl 1.9.8 installed via Homebrew.

**Comment by maebert** [comment]
If you've installed jrnl with homebrew, try:

```bash
brew install dbus
brew services start dbus
```

**Comment by hyiltiz** [comment]
Did `pip install -U keyring`, and `brew install dbus` and `brew services start dbus`. Still getting the same error msg. In my case, the jrnl file has always been in the same computer. I haven't used jrnl for around 18 months, and though I kept by homebrew and OS up to date. Now trying to read old journals by `jrnl -to today`, but that just gives the above error. Even `jrnl today: test` failed.

**Comment by wren** [comment]
Does this still happen with v2.0 with Python 3?

**Comment by cecep2** [comment]
I don't know what caused the issue in the past, but whatever it was, it has been resolved for me. I can install version 1.9.8 on MacOS Mojave via pip without problems.
