### ISSUE TITLE
File name too long on JSON export

### ISSUE THREAD

**Issue by philion** [jrnl-org/jrnl#485]
% jrnl --export json -o journals/
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 251, in run
    print(util.py2encode(exporters.export(journal, args.export, args.output)))
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/exporters.py", line 86, in export
    return write_files(journal, output, format)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/exporters.py", line 112, in write_files
    with codecs.open(full_path, "w", "utf-8") as f:
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 63] File name too long: 'journals/2015-04-23_very-long_sentance-deleted-as-it-contained-personal-details.json'

While generating a title for an entry, a run-on sentence was translated into a file name. Oops. Should probably truncate that.

**Comment by maebert** [comment]
Yeah, that's just silly. Thanks for spotting that!

**Comment by mzfr** [comment]
@maebert 	@wren 	We don't have this problem anymore. We can close this.
