### ISSUE TITLE
1.9.8 - Won't run on Mint 17.3

### ISSUE THREAD

**Issue by chrisodva** [jrnl-org/jrnl#503]
I get a successful install message, but then this on trying to run. Help?

Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography

**Comment by MinchinWeb** [comment]
You're missing the `cryptography` package. I believe it can be installed using `pip`.
