### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by rxa254** [jrnl-org/jrnl#504]
Installed on Mac Sierra using 'pip install jrnl[encrypted]' and trying to read an existing journal.

> jrnl -10
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jrnl/cli.py", line 169, in run
    journal_conf = config['journals'].get(journal_name)
AttributeError: 'unicode' object has no attribute 'get'

**Comment by wren** [comment]
Hi, can you please try with v2.0 and see if you still get this issue?

**Comment by rxa254** [comment]
installed v2; - no error messages when running same command as above
