### ISSUE TITLE
Intermittently unable to access my files

### ISSUE THREAD

**Issue by Asara** [jrnl-org/jrnl#567]
Pretty weird.  If I keep trying the command it will eventually work, but sometimes (usually) it will throw the keyrings error.  I am specifically not adding the password to my keyring btw.  I have the issue on both FreeBSD running v1.9.8 via ports, and on my phone using Termux also v1.9.8 via pip.

```
[asara@host ~]$ jrnl -n 1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python3.4/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[asara@host ~]$ jrnl -n 1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python3.4/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[asara@host ~]$ jrnl -n 1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python3.4/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[asara@host ~]$ jrnl -n 1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python3.4/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[asara@host ~]$ jrnl -n 1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python3.4/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python3.4/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python3.4/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
[asara@host ~]$ jrnl -n 1
Password: 
2019-01-01 23:59 I am going to start keeping a journal.
```

**Comment by Asara** [comment]
Actually, on termux I am only able to access it once.  After that I have to rm my .jrnl_config and then jrnl again in order to access the journal.

**Comment by shadabk96** [comment]
This issue makes the application unusable. What is the expected timeline for the fix?

**Comment by Asara** [comment]
I'm happy to see some traction on https://github.com/jrnl-org/jrnl/issues/591, hopefully this issue gets some attention!

**Comment by wren** [comment]
Are you able to try `v2.0-rc2` to see if you still have the same error?

**Comment by Asara** [comment]
I'm using pip to install jrnl and don't see v2.0-rc2 as an option, even when using `--pre`

**Comment by wren** [comment]
@Asara Good point. It's not listed there, yet. 

@maebert Even though I'm listed as a maintainer, I don't actually have permissions to manage anything with the project on PyPI. Could you please add some permissions?

**Comment by maebert** [comment]
@wren Made you an owner, hope that fixes things

**Comment by Asara** [comment]
Let me know when 2.0-rc2 is pushed to pip and I'll give it a test!

**Comment by maebert** [comment]
@Asara You can now install [rc2](https://pypi.org/project/jrnl/2.0.0rc2/) with `pip install jrnl==2.0.0rc2` (`pip install jrnl` will still install 1.9.8) - let me know how it goes!

**Comment by wren** [comment]
@maebert Thanks for doing that! I had some time set apart today for it, but I'll get a few other things sorted out instead.

**Comment by Asara** [comment]
@wren Just attempted to try this out and I'm bombing out on the same issue as https://github.com/jrnl-org/jrnl/issues/610

I'm on freebsd 12 and also have the same issue.

**Comment by wren** [comment]
@Asara See [this PR](https://github.com/jrnl-org/jrnl/pull/621) for the fix to your problem. You can do that manually, if you're comfortable with it. Or you can wait for v2.0-rc3 if you'd prefer, which I'm trying to get out on Saturday.

**Comment by wren** [comment]
@Asara Have you had a chance to try this, yet? Do you still have this issue?

**Comment by Asara** [comment]
py-cryptography is locked to version 1.4 for jrnl and I'm having a hard time getting that specific version compiled on freebsd 12.  I currently have 2.6.1 installed via ports, so I'm having a tough time testing this specific build

**Comment by wren** [comment]
@Asara I'm closing this issue now that it is merged in to the codebase. This helps avoid confusion for devs working on the project.

Thank you for the work of installing the release candidates, and look for the official v2.0 release soon!
