### ISSUE TITLE
Unable to use jrnl due to json errors

### ISSUE THREAD

**Issue by zrucker** [jrnl-org/jrnl#586]
The errors I am seeing:
> jrnl today: test
Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.8_1/libexec/lib/python3.7/site-packages/jrnl/util.py", line 105, in load_and_fix_json
    return json.loads(json_str)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 5 (char 394)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.8_1/libexec/lib/python3.7/site-packages/jrnl/util.py", line 116, in load_and_fix_json
    config = json.loads(json_str)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 22 (char 23)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8_1/libexec/lib/python3.7/site-packages/jrnl/cli.py", line 141, in run
    config = util.load_and_fix_json(CONFIG_PATH)
  File "/usr/local/Cellar/jrnl/1.9.8_1/libexec/lib/python3.7/site-packages/jrnl/util.py", line 124, in load_and_fix_json
    prompt("[There seems to be something wrong with your jrnl config at {0}: {1}]".format(json_path, e.message))
AttributeError: 'JSONDecodeError' object has no attribute 'message'

**Comment by micahellison** [comment]
It looks there is a problem with your configuration file. Unfortunately, it's hard to tell where it is because the code is hitting an exception when trying to display the path of your configuration file! However it is most likely in your user folder in a file called .jrnl_config as per this link: http://jrnl.sh/advanced.html

If you're comfortable pasting in your configuration file's contents, we might be able to help repair it.
