### ISSUE TITLE
2.0.0-rc3-2: Error when using multiple journals (TypeError: _create() takes exactly 3 arguments (2 given))

### ISSUE THREAD

**Issue by thanateros** [jrnl-org/jrnl#635]
I like that jrnl is back in regular development again! In the past I had problems related to encryption and reluctantly left it for other solutions. Not linking them, I have returned back to see how jrnl is doing after a year away and eagerly loaded up 2.0.0-rc3-2. 

Works great and I noticed no encryption issues.

HOWEVER: when I added more journals to my config file (e.g., 'work') and tried `jrnl work` I received the following error 

```
[Journal 'work' created at /home/nhxjhhh/.local/share/jrnl/work.txt]
Traceback (most recent call last):
  File "/home/nhxjhhh/.local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/home/nhxjhhh/.local/lib/python2.7/site-packages/jrnl/cli.py", line 210, in run
    journal = Journal.open_journal(journal_name, config)
  File "/home/nhxjhhh/.local/lib/python2.7/site-packages/jrnl/Journal.py", line 339, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "/home/nhxjhhh/.local/lib/python2.7/site-packages/jrnl/Journal.py", line 76, in open
    self._create(filename)
TypeError: _create() takes exactly 3 arguments (2 given)
```
My .jrnl_config file:

```json
{    
    "encrypt": true,    
    "journals": {    
        "default": "~/.local/share/jrnl/journal.txt",    
        "work": "~/.local/share/jrnl/work.txt",    
        "food": "~/.local/share/jrnl/recipies.txt"    
    }    
}
```

Also, even though it said it created the work.txt file, it actually did not.

I validated the JSON of the config file in case that was an issue: no problems there that I saw.

I'm not a Python expert, google didn't return any hits on this, and I saw no reference to this in the github issue log, thus I am seeking assistance on this issue.

**Comment by gregorybodnar** [comment]
I bumped into the same thing. I'd worked around this by creating an unencrypted journal in the config file, added an entry to it, and then encrypted it with `jrnl newjournal --encrypt`.

**Comment by wren** [comment]
Hi, thanks for the kind words! I'm glad that this project is getting going again, too!

For your issue: the JSON config file was dropped in v2.0 in favor of YAML. You should be editing the YAML file in your config directory. Can you please confirm that you see the same problem while updating the correct config file?

Also, we're dropping Python 2 support (since it'll no longer be maintained past this year). Can you please upgrade to Python 3 and see if the issue persists?

**Comment by thanateros** [comment]
@gregorybodnar  Hey thanks man, that worked!

**Comment by thanateros** [comment]
@wren Forgot to mention: I am using Python 3; however my dumb@$$ somehow missed the move to the YAML config in .config/jrnl/.  
However, it still didn't help, same error even when starting fresh all over again -- I had to follow @gregorybodnar 's advice above to disable encryption in the YAML, add one entry to each journal so the .txt files were created, then use `jrnl [name_of_journal] --encrypt` on each one, then go back into the config and re-enable encryption -- then it works for me.

Apologies for forgetting to close this when I had my solution.

Aside :: this project inspires me to want to learn python and actively contribute.

**Comment by wren** [comment]
@thanateros No worries! And thanks, again, for the kind words! We're always accepting PRs, so please feel free to contribute if/when you want to learn some Python. :)

**Comment by gregorybodnar** [comment]
I think I see the path to the bug. The `_create` method for `Journal` and `PlainJournal` classes have a different signature than for `EncryptedJournal`, which takes an additional parameter for the password. This is explicitly handled for the default journal in the `install` function in [jrnl/install.py](https://github.com/jrnl-org/jrnl/blob/04811405dc0007dcf1184b885b89bc5c965ddaac/jrnl/install.py#L96). However, when a another journal is added to the configuration file and set to be encrypted, control goes through the `open` method in [jrnl/Journal.py](https://github.com/jrnl-org/jrnl/blob/04811405dc0007dcf1184b885b89bc5c965ddaac/jrnl/Journal.py#L69). Since there's no overload for `EncryptedJournal`,  `_create` is called with only the filename.

I can imagine a couple of approaches to solving this, but I won't have time before the weekend. If someone else can jump on it before then, go for it. Otherwise, I'll try to wrangle together a PR before next week.

@wren Can you reopen this? It should probably be fixed before the final 2.0 release.

**Comment by wren** [comment]
@gregorybodnar Yup! Good catch!

Thanks for jumping on this. I also have some time this weekend, so let me know if you're not going to have time, and I'll take a look.

**Comment by thanateros** [comment]
Neat. It wasn't just me being st00pid this time 😃 And I helped expose a bug. Now I really wanna learn Python and help out on this project.

Thanks for all the help and patience.

**Comment by micahellison** [comment]
Hey @thanateros, just saw this issue and am putting in some work on jrnl today. Are you working on this or would you like me to take a look?

**Comment by micahellison** [comment]
Hey @gregorybodnar, just saw this issue and am putting in some work on jrnl today. Are you working on this or would you like me to take a look?

**Comment by gregorybodnar** [comment]
@micahellison I had a bit of time yesterday and it's mostly going. I'm doing something wrong in the behave script that's causing it to prompt for the initial password for the encrypted file instead of taking it from the entered string, but the tests all pass once it has a password.

I could open the PR for feedback and assistance, since my next block of time will be a few hours away.
