### ISSUE TITLE
Can't use encrypted journal on Windows 10 - TypeError: putwch() argument must be a unicode character, not int

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#667]
In v2.0.0, when I try to make an encrypted journal in Windows 10, I get a Python error.

I defined a new encrypted journal "enc" in my jrnl.yaml:
``` yaml
journals:
  default: C:\Users\micah\.local\share\jrnl\journal.txt
  enc:
    journal: C:\Users\micah\.local\share\jrnl\enc.txt
    encrypt: true
```

Then I tried to write an entry to it from the shell:
```
C:\Users\micah>jrnl enc testing
Traceback (most recent call last):
  File "C:\Python37\Scripts\jrnl-script.py", line 11, in <module>
    load_entry_point('jrnl==2.0.0', 'console_scripts', 'jrnl')()
  File "c:\python37\lib\site-packages\jrnl\cli.py", line 210, in run
    journal = Journal.open_journal(journal_name, config)
  File "c:\python37\lib\site-packages\jrnl\Journal.py", line 359, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "c:\python37\lib\site-packages\jrnl\EncryptedJournal.py", line 42, in open
    password = util.getpass("Enter password for new journal: ")
  File "c:\python37\lib\site-packages\jrnl\util.py", line 52, in getpass
    return gp.getpass(bytes(prompt))
  File "c:\python37\lib\getpass.py", line 103, in win_getpass
    msvcrt.putwch(c)
TypeError: putwch() argument must be a unicode character, not int
```

**Comment by BeardedIT** [comment]
I too am experiencing this issue
