### ISSUE TITLE
Failure to run Arch Linux 

### ISSUE THREAD

**Issue by kcallis** [jrnl-org/jrnl#673]
My **Arch Linux** installed [*jrnl-git 0.r775.350f0a1-1*](https://aur.archlinux.org/packages/jrnl-git/) and since then, when I attempt to make use of jrnl, I get the following message:

```bash
[kcc@elite ~]$ jrnl -ls
Traceback (most recent call last):
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/bin/jrnl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/kcc/.cache/pypoetry/virtualenvs/jrnl-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jrnl' distribution was not found and is required by the application
```
I am running under python 3.7, and have made sure to have installed *python-keyrings-alt* and poetry. I am now dwelling into *virtualenvs* and that is starting to get out of my depth.

**Comment by wren** [comment]
Hrmm, I'm not sure where that package came from. The only currently supported install method is `pip install jrnl`. Do you happen to know where jrnl-git came from?

**Comment by kcallis** [comment]
Yes, it is located on the AUR Package Community Site. The package is named **[jrnl-git]**(https://aur.archlinux.org/packages/jrnl-git/). Unless some wires got tangled!

**Comment by kcallis** [comment]
Interestingly enough, I did another "*pip install jrnl*" and everything ran like it was suppose to. It would seem that I am now using version 2 of jrnl, but I am happy to be back to gather my thoughts again.
