### ISSUE TITLE
[DayOne] IsADirectoryError while upgrading

### ISSUE THREAD

**Issue by my-flow** [jrnl-org/jrnl#689]
Trying to upgrade from version 1.9.8 (installed via Homebrew) to version 2.0.1 (installed via `pip3`). Using [DayOne integration](https://jrnl.sh/advanced/#dayone-integration) with iCloud synchronization. Upgrade procedure complains that `~/Library/Mobile
    Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/` is a directory (which it is).

```
florian@nighttrain:~ $ jrnl -ls
Welcome to jrnl v2.0.1.

It looks like you've been using an older version of jrnl until now. That's
okay - jrnl will now upgrade your configuration and journal files. Afterwards
you can enjoy all of the great new features that come with jrnl 2:

- Support for storing your journal in multiple files
- Faster reading and writing for large journals
- New encryption back-end that makes installing jrnl much easier
- Tons of bug fixes

Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
If you choose to proceed, you will not be able to use your journals with
older versions of jrnl anymore.

Following plain text journals will upgraded to jrnl v2.0.1:
    default -> ~/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone
Continue upgrading jrnl? [y/N]
y

Upgrading plain text 'default' journal stored in ~/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone...
  Created a backup at ~/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone.backup
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 148, in run
    config = install.load_or_install_jrnl()
  File "/usr/local/lib/python3.7/site-packages/jrnl/install.py", line 92, in load_or_install_jrnl
    upgrade.upgrade_jrnl_if_necessary(config_path)
  File "/usr/local/lib/python3.7/site-packages/jrnl/upgrade.py", line 95, in upgrade_jrnl_if_necessary
    backup(path)
  File "/usr/local/lib/python3.7/site-packages/jrnl/upgrade.py", line 15, in backup
    with open(filename, 'rb' if binary else 'r') as original:
IsADirectoryError: [Errno 21] Is a directory: '/Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone'
```

**Comment by wren** [comment]
@MinchinWeb Can you take a look at this Day One-related bug?

**Comment by MinchinWeb** [comment]
@my-flow : Are you using DayOne "Classic" or DayOne 2?

Can you provide a file listing (`ls`...) of the DayOne directory?

**Comment by my-flow** [comment]
I use DayOne Classic:
- DayOne for macOS version 1.9.
- DayOne for iOS version 1.17.9

```
florian@nighttrain:~ $ ls "/Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone"
Permissions Size User    Date Modified Name
drwxr-xr-x     - florian 24 Oct 23:24  /Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone
.rw-r--r--@ 6.1k florian  7 Oct  0:26  ├── .DS_Store
drwxr-xr-x     - florian 21 Aug 11:52  ├── duplicateEntries
drwxr-xr-x     - florian 21 Aug 11:52  ├── duplicatePhotos
drwxr-xr-x     - florian 24 Oct 23:24  ├── entries
drwxr-xr-x     - florian  8 Sep 21:21  ├── photos
.rw-r--r--@  640 florian  4 Apr  2013  └── security.plist
```

**Comment by MinchinWeb** [comment]
Thanks @my-flow , this is what I was expecting to see. I need to look into the upgrade script.

If you want to upgrade now, you should be able to by removing this journal from your config file, upgrading and re-adding it to your config file.

I'll post here once we have a working "proper" solution.

**Comment by MinchinWeb** [comment]
@my-flow Does upgrading work if you change your config to use the "full" folder path (`/Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone`) (rather than relying on `~` expansion...)?

**Comment by my-flow** [comment]
> @my-flow Does upgrading work if you change your config to use the "full" folder path (`/Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone`) (rather than relying on `~` expansion...)?

I tried this now. The upgrade routine succeeded and there is no `IsADirectoryError` error anymore. Still, I suggest to support `~` expansion.

After upgrading I received an `IndexError: list index out of range` when trying to [list all entries](https://jrnl.sh/export/#list-of-all-entries):

```
florian@nighttrain:~ $ jrnl -ls
Welcome to jrnl v2.0.1.

It looks like you've been using an older version of jrnl until now. That's
okay - jrnl will now upgrade your configuration and journal files. Afterwards
you can enjoy all of the great new features that come with jrnl 2:

- Support for storing your journal in multiple files
- Faster reading and writing for large journals
- New encryption back-end that makes installing jrnl much easier
- Tons of bug fixes

Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
If you choose to proceed, you will not be able to use your journals with
older versions of jrnl anymore.

Following journals will be not be touched:
    default -> /Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone
Continue upgrading jrnl? [y/N]
y

Upgrading config...
  Created a backup at /Users/florian/.jrnl_config.backup

We're all done here and you can start enjoying jrnl 2.
[Configuration updated to newest version at /Users/florian/.config/jrnl/jrnl.yaml]
Journals defined in /Users/florian/.config/jrnl/jrnl.yaml
 * default -> /Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone

florian@nighttrain:~ $ jrnl -ls
Journals defined in /Users/florian/.config/jrnl/jrnl.yaml
 * default -> /Users/florian/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone

florian@nighttrain:~ $ jrnl --short
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 253, in run
    print(util.py2encode(journal.pprint(short=True)))
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 149, in pprint
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 149, in <listcomp>
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 93, in pprint
    title = date_str + " " + self.title.rstrip("\n ")
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 37, in title
    self._parse_text()
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 27, in _parse_text
    if lines[0].strip().endswith("*"):
IndexError: list index out of range
```

[`jrnl -until "last year"`](https://jrnl.sh/usage/#viewing) gave me a similar error:
```
florian@nighttrain:~ $ jrnl -until "last year"
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 249, in run
    print(util.py2encode(journal.pprint()))
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 149, in pprint
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 149, in <listcomp>
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 82, in pprint
    title = textwrap.fill(date_str + " " + self.title, self.journal.config['linewrap'])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 37, in title
    self._parse_text()
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 27, in _parse_text
    if lines[0].strip().endswith("*"):
IndexError: list index out of range
```

[JSON export](https://jrnl.sh/export/#json-export) gave me a similar error:
```
florian@nighttrain:~ $ jrnl --export json
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 260, in run
    print(exporter.export(journal, args.output))
  File "/usr/local/lib/python3.7/site-packages/jrnl/plugins/text_exporter.py", line 62, in export
    return cls.export_journal(journal)
  File "/usr/local/lib/python3.7/site-packages/jrnl/plugins/json_exporter.py", line 39, in export_journal
    "entries": [cls.entry_to_dict(e) for e in journal.entries]
  File "/usr/local/lib/python3.7/site-packages/jrnl/plugins/json_exporter.py", line 39, in <listcomp>
    "entries": [cls.entry_to_dict(e) for e in journal.entries]
  File "/usr/local/lib/python3.7/site-packages/jrnl/plugins/json_exporter.py", line 18, in entry_to_dict
    'title': entry.title,
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 37, in title
    self._parse_text()
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 27, in _parse_text
    if lines[0].strip().endswith("*"):
IndexError: list index out of range
```

I am not sure if these are follow-up bugs related to Day One.
