### ISSUE TITLE
ImportError: cannot import name winconstants

### ISSUE THREAD

**Issue by mrkreen** [jrnl-org/jrnl#71]
Another issue trying to install 56a9c0bbcc this afternoon:

Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    load_entry_point('jrnl==1.0.4', 'console_scripts', 'jrnl')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1954, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "build/bdist.macosx-10.8-intel/egg/jrnl/**init**.py", line 15, in <module>
  File "build/bdist.macosx-10.8-intel/egg/jrnl/Journal.py", line 15, in <module>
  File "build/bdist.macosx-10.8-intel/egg/readline.py", line 6, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pyreadline/**init**.py", line 11, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pyreadline/modes/**init**.py", line 3, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pyreadline/modes/emacs.py", line 16, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pyreadline/modes/basemode.py", line 14, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pyreadline/keysyms/**init**.py", line 7, in <module>
ImportError: cannot import name winconstants

Sorry if this is my lack of python/unix knowledge; just trying to get this to work. Thanks again for the help.

**Comment by baluKanattil** [comment]
I am getting the same error. jrnl was working fine until I installed a few python packages like ipython, numpy, scipy and pandas. Now whenever i run jrnl i get an importerror for winconstants.
