### ISSUE TITLE
jrnl crashes on start with Windows ActivePython due to readline

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#738]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: 2.1.0
  - How you installed Jrnl: see below
  - Operating system [MacOS, Linux, Windows?] Windows 10

* **What is the current behavior?**
I didn't have this problem until I started using poetry, which uses ActivePython when I kick off a shell. It turns out that ActivePython isn't compatible with the GNU license, and the readline module is GNU, so it simple doesn't provide that module.

As far as I can tell, this needs to be resolved to enable a Windows build in Travis.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
From the console:

```
C:\dev\jrnl>poetry shell
Spawning shell within C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7
Microsoft Windows [Version 10.0.17763.805]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\dev\jrnl>poetry install
Installing dependencies from lock file

Nothing to install or update

  - Installing jrnl (v2.1.post2)

C:\dev\jrnl>jrnl
Traceback (most recent call last):
  File "C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7\Scripts\jrnl-script.py", line 11, in <module>
    load_entry_point('jrnl', 'console_scripts', 'jrnl')()
  File "C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\micah\AppData\Local\pypoetry\Cache\virtualenvs\jrnl-py3.7\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\dev\jrnl\jrnl\cli.py", line 11, in <module>
    from . import install
  File "c:\dev\jrnl\jrnl\install.py", line 3, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Looks like maybe pyreadline is a good alternative? Except the max Python version it supports is 3.5.
https://pypi.org/project/pyreadline/

**Comment by zeruhur** [comment]
Same for me... 
just installed jrnl on windows via pip,
when I call it this traceback is displayed:
```
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\jrnl.exe\__main__.py", line 5, in <module>
  File "c:\program files\python37\lib\site-packages\jrnl\cli.py", line 14, in <module>
    from . import install
  File "c:\program files\python37\lib\site-packages\jrnl\install.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Comment by moin1958** [comment]
I just installed jrnl on windows 10 via pip after installing python 3.7,
when I call it this traceback is displayed:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\jrnl.exe\__main__.py", line 5, in <module>
  File "c:\program files\python37\lib\site-packages\jrnl\cli.py", line 14, in <module>
    from . import install
  File "c:\program files\python37\lib\site-packages\jrnl\install.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

Please advise any solution and how to start jrnl?

**Comment by wren** [comment]
@moin1958 What version of jrnl do you have installed? There was a fix for this crash in v2.1.1. Do you have an older version? If so, please reinstall jrnl and try again.

**Comment by codeslord** [comment]
Install pyreadline instead of readline.

`pip install pyreadline`

This should fix the issue

**Comment by SpeedySparrow** [comment]
jrnl version v2.2 / Python 3.7.3 / Windows 10 - getting this error as well. Tried the pyreadline but no luck.
Traceback (most recent call last):
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\user\xxxxxxxx\AppData\Local\Programs\Python\Python37\Scripts\jrnl.exe\__main__.py", line 7, in <module>
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\site-packages\jrnl\cli.py", line 362, in run
    journal = open_journal(journal_name, config)
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\site-packages\jrnl\Journal.py", line 391, in open_journal
    return PlainJournal(name, **config).open()
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\site-packages\jrnl\Journal.py", line 80, in open
    self.create_file(filename)
  File "c:\user\xxxxxxxx\appdata\local\programs\python\python37\lib\site-packages\jrnl\Journal.py", line 105, in create_file
    with open(filename, "w"):
FileNotFoundError: [Errno 2] No such file or directory: "C:\\Users\\thansen31.EAD\\'OneDrive - DXC Production'\\jrnl"
