### ISSUE TITLE
[DayOne] Listing all entries throws IndexError

### ISSUE THREAD

**Issue by my-flow** [jrnl-org/jrnl#780]
I upgraded from version **1.9.8** (installed via Homebrew) to version **2.1.1** (installed via `pip3`).
```
fbreunig@nighttrain:~ $ jrnl --version
jrnl version 2.1.1
```

I’m using [DayOne Classic integration](https://github.com/jrnl-org/jrnl/blob/f0f26a18eb3304aff5ea53e669802a18a2f85e5a/advanced/index.html#L194) with iCloud synchronization (find details in #689).
```
fbreunig@nighttrain:~ $ jrnl -ls
Journals defined in /Users/fbreunig/.config/jrnl/jrnl.yaml
 * default -> ~/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone

```

After upgrading I receive an `IndexError: list index out of range` when trying to [list all entries](https://jrnl.sh/export/#list-of-all-entries):
```
fbreunig@nighttrain:~ $ jrnl --short
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 248, in run
    print(journal.pprint(short=True))
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 148, in pprint
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Journal.py", line 148, in <listcomp>
    pp = sep.join([e.pprint(short=short) for e in self.entries])
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 91, in pprint
    title = date_str + " " + self.title.rstrip("\n ")
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 35, in title
    self._parse_text()
  File "/usr/local/lib/python3.7/site-packages/jrnl/Entry.py", line 25, in _parse_text
    if lines[0].strip().endswith("*"):
IndexError: list index out of range
```

**Comment by wren** [comment]
@MinchinWeb

**Comment by MinchinWeb** [comment]
@my-flow You seem to have a "title only" entry. I guess somewhere it was assumed that an entry would always have a text body...

@wren c.f. #786 to fix this. Do we have a changelog that should be updated with these changes?
