### ISSUE TITLE
How to restore my journal after failed encryption

### ISSUE THREAD

**Issue by pfeffer90** [jrnl-org/jrnl#787]
### Problem
I have been using jrnl for almost two years. Today, I decided to encrypt the existing entries in my default jrnl. 
```
jrnl --encrypt
```

After setting a password, I opted for adding the password to the keyring and this failed
```
Do you want to store the password in your keychain? [Y/n]
Y
Traceback (most recent call last):
  File "/home/pfeiffer/Applications/miniconda2/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/cli.py", line 257, in run
    encrypt(journal, filename=args.encrypt)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/cli.py", line 81, in encrypt
    util.set_keychain(journal.name, password)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/util.py", line 65, in set_keychain
    keyring.set_password('jrnl', journal_name, password)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/keyring/core.py", line 47, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```
Now I cannot read my previous entries anymore. 
```
jrnl
Traceback (most recent call last):
  File "/home/pfeiffer/Applications/miniconda2/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/site-packages/jrnl/Journal.py", line 108, in open
    journal = f.read()
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/codecs.py", line 688, in read
    return self.reader.read(size)
  File "/home/pfeiffer/Applications/miniconda2/lib/python2.7/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 2-3: invalid continuation byte
```
When I try to decrypt `jrnl --decrypt` from jrnl I get the same error.

### What I would like to achieve?

I want to continue using jrnl and restore my previous entries. 

### What I have tried?

I used the manualy decryption script from the [documentation](https://jrnl.sh/encryption/). This works. So I suppose that it is a problem with getting the password from the keyring.

### Environment
Linux
jrnl version 1.9.8

**Comment by pfeffer90** [comment]
Writing down the problem is half the solution :) 

I fixed it in the following way. First, I decrypted the file manually with the script from the documentation, [](https://jrnl.sh/encryption/) and replaced the encrypted file. Then I could regain the entries from jrnl.
To fix the keyring issue, I installed the package secretstorage via conda. Now my journal is encrypted.

**Comment by wren** [comment]
@pfeffer90 I'm glad you worked this out on your own without any data loss. Also, you might want to take a look at updating to v2 branch of jrnl. This bug (#654) was fixed already.

P.S. I know what we've fixed isn't super clear right now due to lack of changelog, but we're working on that.
