### ISSUE TITLE
unhandled exception on install with unsaved password

### ISSUE THREAD

**Issue by dbxnr** [jrnl-org/jrnl#788]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`)
2.1.1
  - How you installed Jrnl
pip
  - Operating system [MacOS, Linux, Windows?]
linux

* **What is the current behavior?**
Running jrnl for the first time, creating an encrypted journal and choosing not to store the password in keychain raises an unhandled exception.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
```
x@y:~$ jrnl
Path to your journal file (leave blank for /home/x/.local/share/jrnl/journal.txt): 
Enter password for journal (leave blank for no encryption): 
Do you want to store the password in your keychain? [Y/n] n
Traceback (most recent call last):
  File "/home/x/.local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/home/x/.local/lib/python3.7/site-packages/jrnl/cli.py", line 144, in run
    config = install.load_or_install_jrnl()
  File "/home/x/.local/lib/python3.7/site-packages/jrnl/install.py", line 106, in load_or_install_jrnl
    config = install()
  File "/home/x/.local/lib/python3.7/site-packages/jrnl/install.py", line 136, in install
    util.set_keychain("default", None)
  File "/home/x/.local/lib/python3.7/site-packages/jrnl/util.py", line 75, in set_keychain
    keyring.delete_password('jrnl', journal_name)
  File "/home/x/.local/lib/python3.7/site-packages/keyring/core.py", line 68, in delete_password
    _keyring_backend.delete_password(service_name, username)
  File "/home/x/.local/lib/python3.7/site-packages/keyring/backends/chainer.py", line 57, in delete_password
    return keyring.delete_password(service, username)
  File "/home/x/.local/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 99, in delete_password
    raise PasswordDeleteError("No such password!")
keyring.errors.PasswordDeleteError: No such password!
```

* **What is the expected behavior?**
jrnl would create a new encrypted journal without saving the password.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wren** [comment]
Thank you for the issue. Also, thank you for all the PRs! It's great to see some contribute so much.

We'll be reviewing all of them soon, and should get them merged into the next version.
