### ISSUE TITLE
Good place for install assistance?

### ISSUE THREAD

**Issue by pawlowski6132** [jrnl-org/jrnl#816]
Team, this seems to be a JRNL issues list but, I'm really looking for some guidance on what I'm sure is user error. I suspect install was not successful. After I install and try to post an entry, I get this:

jrnl yesterday: Test title. This is body text.
Traceback (most recent call last):
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\cli.py", line 216, in run
    journal = Journal.open_journal(journal_name, config)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\Journal.py", line 364, in open_journal       
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\EncryptedJournal.py", line 56, in open       
    text = self._load(filename)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\EncryptedJournal.py", line 82, in _load      
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\util.py", line 63, in get_password
    password = pwd_from_keychain or getpass()
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\util.py", line 56, in getpass
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\getpass.py", line 103, in win_getpass
    msvcrt.putwch(c)
TypeError: putwch() argument must be a unicode character, not int
PS C:\Users\pawlo\Documents\python_tst> cd c:\users\pawlow\appdata\local\programs\python\
cd : Cannot find path 'C:\users\pawlow\appdata\local\programs\python\' because it does not exist.
At line:1 char:1
+ cd c:\users\pawlow\appdata\local\programs\python\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\users\pawlow...rograms\python\:String) [Set-Location], ItemNotFoundException       
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
PS C:\Users\pawlo\Documents\python_tst> jrnl -ls
Journals defined in C:\Users\pawlo\.config\jrnl\jrnl.yaml
 * default -> C:\Users\pawlo\.local\share\jrnl\journal.txt

PS C:\Users\pawlo\Documents\python_tst> jrnl yesterday: Test title. Body test.
Traceback (most recent call last):
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pawlo\AppData\Local\Programs\Python\Python38-32\Scripts\jrnl.exe\__main__.py", line 9, in <module>
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\cli.py", line 216, in run
    journal = Journal.open_journal(journal_name, config)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\Journal.py", line 364, in open_journal       
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\EncryptedJournal.py", line 56, in open       
    text = self._load(filename)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\EncryptedJournal.py", line 82, in _load      
    return util.get_password(keychain=self.name, validator=validate_password)
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\util.py", line 63, in get_password
    password = pwd_from_keychain or getpass()
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\site-packages\jrnl\util.py", line 56, in getpass
    return gp.getpass(bytes(prompt))
  File "c:\users\pawlo\appdata\local\programs\python\python38-32\lib\getpass.py", line 103, in win_getpass
    msvcrt.putwch(c)
TypeError: putwch() argument must be a unicode character, not int

I'm running Windows 10 and Python 3.8. 

Anywho, this looks like a super cool, simple tool. I'm looking forward to using this.

**Comment by micahellison** [comment]
Hi there! Thanks for reporting this issue, and for the kind words.

While your error message looks unfamiliar, I think this may be fixed in the [2.2 beta](https://pypi.org/project/jrnl/2.2b0/) release. Could you try running `pip install jrnl==2.2b0` and seeing if that helps?

And if it still doesn't work, could you please specify which Windows [Python distribution](https://wiki.python.org/moin/PythonDistributions) you're using?

**Comment by pawlowski6132** [comment]
That worked! Thanx so much. Can't wait to start using this. Great job!
