### ISSUE TITLE
fresh install will not run

### ISSUE THREAD

**Issue by C0deGyver** [jrnl-org/jrnl#832]
## Bug report
for the version of jrnl I am running I just installed it fresh today 2/7/2020
I installed it using pip install jrnl
installed on Ubuntu 18.04.4 and kernel 4.15.0-76-generic

When I try to run jrnl i get the below error
`Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jrnl==2.0.0rc3' distribution was not found and is required by the application`

I hae tried installing it with pip2 ans pip3 specifically as well with the same results

**Comment by micahellison** [comment]
Thanks for the error report. Are you able to run `jrnl --version` and if so, could you paste the output? I'm a little surprised by the reference to jrnl==2.0.0rc3, which is a version that doesn't exist.

**Comment by C0deGyver** [comment]
When I run that I get the same message

**Comment by micahellison** [comment]
I'm wondering if your machine is somehow pointing to an out-of-date pypi repository, though I don't know much about how that works. Could you try explicitly installing the latest version like so:
```
pip uninstall jrnl
pip install jrnl==2.2
```

**Comment by wren** [comment]
Agreed. `jrnl==2.0.0rc3` is a very old version. Please let us know if you have the same problem with the latest (`v2.2`).

**Comment by C0deGyver** [comment]
that worked. I also tried it after pip upgrade with out issues) I assumed that if pip needed upgraded it would tell me... that would be a no :(
