### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 3: invalid start byte

### ISSUE THREAD

**Issue by mileslauridsen** [jrnl-org/jrnl#834]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`)
           jrnl version v2.2
  - How you installed Jrnl
          pip install jrnl --upgrade
          Upgraded from 1.9.8
  - Operating system [MacOS, Linux, Windows?]
          MacOS 10.14.6

* **What is the current behavior?**
Fails to upgrade encrypted jrnl files from 1.9.8 to 2.2

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
Welcome to jrnl v2.2.

It looks like you've been using an older version of jrnl until now. That's
okay - jrnl will now upgrade your configuration and journal files. Afterwards
you can enjoy all of the great new features that come with jrnl 2:

- Support for storing your journal in multiple files
- Faster reading and writing for large journals
- New encryption back-end that makes installing jrnl much easier
- Tons of bug fixes

Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
If you choose to proceed, you will not be able to use your journals with
older versions of jrnl anymore.


Following encrypted journals will be upgraded to jrnl v2.2:
    default -> /Users/user/journal.txt

Following plain text journals will upgraded to jrnl v2.2:
    work    -> /Users/user/work.txt
Continue upgrading jrnl? [y/N] y

Upgrading encrypted 'default' journal stored in /Users/user/journal.txt...
  Created a backup at /Users/user/journal.txt.backup
Password: 

Upgrading plain text 'work' journal stored in /Users/user/work.txt...
  Created a backup at /Users/user/work.txt.backup
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/jrnl/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/Users/user/.pyenv/versions/3.6.8/envs/jrnl/lib/python3.6/site-packages/jrnl/cli.py", line 286, in run
    config = install.load_or_install_jrnl()
  File "/Users/user/.pyenv/versions/3.6.8/envs/jrnl/lib/python3.6/site-packages/jrnl/install.py", line 102, in load_or_install_jrnl
    upgrade.upgrade_jrnl_if_necessary(config_path)
  File "/Users/user/.pyenv/versions/3.6.8/envs/jrnl/lib/python3.6/site-packages/jrnl/upgrade.py", line 122, in upgrade_jrnl_if_necessary
    backup(path)
  File "/Users/user/.pyenv/versions/3.6.8/envs/jrnl/lib/python3.6/site-packages/jrnl/upgrade.py", line 15, in backup
    contents = original.read()
  File "/Users/user/.pyenv/versions/3.6.8/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 3: invalid start byte
```

**Comment by micahellison** [comment]
Thanks for the bug report. Would you be comfortable sharing your `~/.jrnl_config` file here?

It looks like jrnl v2.2 is parsing your `work.txt` as a plaintext journal whereas perhaps jrnl 1.9.8 was treating it as an encrypted journal. The configuration file could help us understand what's happening exactly.

**Comment by mileslauridsen** [comment]
Hi @micahellison 

Here's my config, which I believe worked with the older version of jrnl i was using.

```
{
  "default_hour": 9,
  "linewrap": 79,
  "encrypt": true,
  "default_minute": 0,
  "tagsymbols": "@",
  "editor": "subl -w",
  "timeformat": "%Y-%m-%d %H:%M",
  "highlight": true,
  "journals": {
    "default": {
      "journal": "/Users/user/journal.txt",
      "encrypt": true
    },
    "work": {
      "journal": "/Users/user/work.txt",
      "encyrpt": true
    }
  }
}
```

**Comment by micahellison** [comment]
I see. There's an `encyrpt` typo in your config file under "work" -- I think correcting it to `encrypt` will resolve the problem:

```
      "encyrpt": true
```

**Comment by mileslauridsen** [comment]
Ahh, operator error bug. Thanks so much for catching that!
