### ISSUE TITLE
Keyring issue

### ISSUE THREAD

**Issue by jonaths** [jrnl-org/jrnl#847]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`): jrnl version v2.0.1
  - How you installed Jrnl: through pip install jrnl and then modifying the bashrc so it is accesible. 
  - Operating system [MacOS, Linux, Windows?]: Ubuntu 18

* **What is the current behavior?**
After installation and after trying to type the first journal this error appears. 

ERROR    keyring.backend Error initializing plugin EntryPoint('Windows (alt)', u'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/jonathan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/jonathan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape
ERROR    keyring.backend Error initializing plugin EntryPoint('file', u'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/jonathan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/jonathan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape
ERROR    keyring.backend Error initializing plugin EntryPoint('pyfs', u'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/jonathan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/jonathan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
Install and run jrnl. The program asks for the location and then asks for the first entry. Then the error appears. 

* **What is the expected behavior?**
Normally I would type in my journal and it would save it into my file. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by micahellison** [comment]
jrnl 2+ doesn't support Python 2. You can install jrnl 1.9.8 like so:
```
pip install jrnl==1.9.8
```
Or you can use Python 3 to install the latest version:
```
pip install jrnl==2.2
```

**Comment by jonaths** [comment]
Thanks! I tried to install version 1.9.8. It was successfully installed but then when trying to add a new entry this message appears.

-> jrnl -v
No handlers could be found for logger "keyring.backend"
jrnl version 1.9.8

-> jrnl
No handlers could be found for logger "keyring.backend"
[Compose Entry; press Ctrl+D to finish writing]

**Comment by micahellison** [comment]
Upon further examination, it looks like that this is a bug fixed in later versions. However, you'll need to upgrade Python to 3.6 or later to run it.

**Comment by wren** [comment]
@jonaths Did you try to upgrade? Did it fix your issue?

**Comment by jonaths** [comment]
@wren I am able to use jrnl 2.2 with python 2.7 unencrypted. I have not tried again to upgrade. Ill try tomorrow and let you know. Thanks for the follow up!
