### ISSUE TITLE
can't get vs code to work as editor in win 10, and can't find solution in documentation

### ISSUE THREAD

**Issue by musclecups** [jrnl-org/jrnl#856]
## Support request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**

  - Jrnl version: (run `jrnl -v`)
v2.2
  - How you installed Jrnl
via pip
  - Operating system [MacOS, Linux, Windows?]
windows 10
* **What are you trying to do?**
use VS code as editor
* **What have you tried?**
editor: "code -w"
editor: "code --wait"
editor: "code"
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
-code is added to path and launches when invoked from command prompt
-editor: "subl -w" works as intended

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\jrnl.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\jrnl\cli.py", line 344, in run
    raw = util.get_text_from_editor(config, template)
  File "c:\program files\python36\lib\site-packages\jrnl\util.py", line 153, in get_text_from_editor
    shlex.split(config["editor"], posix="win" not in sys.platform) + [tmpfile]
  File "c:\program files\python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\program files\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

thanks!

**Comment by micahellison** [comment]
It looks like it can't find `code` for whatever reason. The symptoms are the same as specifying an executable that doesn't exist in the `editor` field. Maybe the PATH variable isn't set correctly in the particular shell session you're running jrnl in.

Whatever the case, you could try using the full path as a workaround. I installed VS Code and tried using the full path in single quotes, and that worked for me:
```
editor: 'C:\Users\micah\AppData\Local\Programs\Microsoft VS Code\Code.exe -w'
```

**Comment by musclecups** [comment]
Thanks so much -- that got it working right away.  Sorry for bothering you with trivial beginner questions, but I really appreciate your help.
