### ISSUE TITLE
Please help me getting jrnl to work

### ISSUE THREAD

**Issue by SimplePhysician** [jrnl-org/jrnl#863]
I will start by saying thank you for whoever will put his time into helping me in this situation.

I have installed jrnl on macOS catalina using brew.
I think the error I'm getting might have something to do with me having it installed previously, although I don't remember actually using it.
Thinking that it might have had something to do with decrypting some files I had used before, I just erased a bunch of files which admittedly wasn't very smart.

If I type any command (i.e. "jrnl help" or "jrnl today: test") I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/util.py", line 39, in get_password
    result = validator(password)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 98, in validate_password
    return self._decrypt(journal_encrypted)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 51, in _decrypt
    crypto = AES.new(self.key, AES.MODE_CBC, cipher[:16])
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long`

**Comment by micahellison** [comment]
Hi there! Unfortunately, jrnl's brew install is broken right now (but so close to being fixed!). In the meantime, you can replace your jrnl installation with the latest, functional version by using the following commands:
```
brew uninstall jrnl
brew tap jrnl-org/prerelease
brew install jrnl-beta
```

**Comment by SimplePhysician** [comment]
Thank you for the quick reply. I have installed the new version and it prompts me to update the previous file (I don't know how jrnl was set to find something in my Google Drive folder, assuming that's how I set it up some years ago, I went ahead and created the folders and files it was expecting lol). I'm not getting this error instead:

Upgrading encrypted 'default' journal stored in /Users/federicoballacci/Google Drive/Documenti/jrnl/journal.txt...
  Created a backup at /Users/federicoballacci/Google Drive/Documenti/jrnl/journal.txt.backup
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/cli.py", line 286, in run
    config = install.load_or_install_jrnl()
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/install.py", line 102, in load_or_install_jrnl
    upgrade.upgrade_jrnl_if_necessary(config_path)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/upgrade.py", line 113, in upgrade_jrnl_if_necessary
    journal_name, util.scope_config(config, journal_name), legacy=True
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/Journal.py", line 396, in open_journal
    return EncryptedJournal.LegacyEncryptedJournal(name, **config).open()
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/Journal.py", line 83, in open
    text = self._load(filename)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/EncryptedJournal.py", line 132, in _load
    return util.decrypt_content(keychain=self.name, decrypt_func=decrypt_journal)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/util.py", line 74, in decrypt_content
    result = decrypt_func(password)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/jrnl/EncryptedJournal.py", line 115, in decrypt_journal
    algorithms.AES(decryption_key), modes.CBC(iv), default_backend()
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 108, in __init__
    mode.validate_for_algorithm(algorithm)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/modes.py", line 82, in _check_iv_and_key_length
    _check_iv_length(self, algorithm)
  File "/usr/local/Cellar/jrnl-beta/2.2/libexec/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/modes.py", line 76, in _check_iv_length
    len(self.initialization_vector), self.name
ValueError: Invalid IV size (1) for CBC.

**Comment by micahellison** [comment]
Glad to help! From the looks of it, I think it might be trying to decrypt a journal that isn't encrypted, but I'm not sure.

If you're not interested in that old journal at all, try deleting your old config file. It should be in `~/.config/jrnl/` I believe.

**Comment by SimplePhysician** [comment]
I am not interested in the old journal and starting from scratch would be really an ideal scenario.
In the config folder I have 2 folders names "jrnl" and "jrnl 21.28.09" but both of them are empty.
Looks like I have messed up back then!

**Comment by SimplePhysician** [comment]
Looks like I found it under ~/.jrnl_config. Thank you very much!

**Comment by micahellison** [comment]
Whoops! Sorry for leading you astray with that path. Glad it's working now!
