### ISSUE TITLE
Getting past initial installation

### ISSUE THREAD

**Issue by heydonovan** [jrnl-org/jrnl#877]
## Support request

```
$ jrnl -v
jrnl version v2.2
```

Just installed jrnl for the first time using `brew install jrnl`. Currently receive the following:

```
$ jrnl yesterday: Called in sick. Used the time to clean the house and spent 4h on writing my book.
[Error: /Users/heydonovan is a directory, but doesn't seem to be a DayOne journal either.
```

I'm on macOS 10.14.6. Looking at my scrollback, here is the first command I tried:

```
$ jrnl
/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/time.py:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if flag is 1:  # Date found, but no time. Use the default time.
Path to your journal file (leave blank for /Users/heydonovan/.local/share/jrnl/journal.txt): ~
Do you want to encrypt your journal? You can always change this later [y/N] y
Journal will be encrypted.
[Compose Entry; press Ctrl+D to finish writing]

test
[Error: /Users/heydonovan is a directory, but doesn't seem to be a DayOne journal either.
```

```
$ rm /Users/heydonovan/.local/share/jrnl/journal.txt
rm: /Users/heydonovan/.local/share/jrnl/journal.txt: No such file or directory
```

```
$ rm ~/.config/jrnl/jrnl.yaml
```

```
$ jrnl
Path to your journal file (leave blank for /Users/heydonovan/.local/share/jrnl/journal.txt):
Do you want to encrypt your journal? You can always change this later [y/N] y
Journal will be encrypted.
[Compose Entry; press Ctrl+D to finish writing]


Enter password for new journal:
Enter password again:
Do you want to store the password in your keychain? [Y/n] n
Encrypted journal 'default' created at /Users/heydonovan/.local/share/jrnl/journal.txt
[Entry added to default journal]
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 377, in run
    journal.write()
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 92, in write
    text = self._to_text()
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 109, in _to_text
    return "\n".join([str(e) for e in self.entries])
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 109, in <listcomp>
    return "\n".join([str(e) for e in self.entries])
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Entry.py", line 64, in __str__
    title = "[{}] {}".format(date_str, self.title.rstrip("\n "))
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Entry.py", line 35, in title
    self._parse_text()
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Entry.py", line 25, in _parse_text
    if lines[0].strip().endswith("*"):
IndexError: list index out of range
```

**Comment by wren** [comment]
Looks like you ran into #878. We'll get a fix for that in on the next version.

Out of curiosity, what was your date format set to when you saw this?

**Comment by heydonovan** [comment]
> Looks like you ran into #878. We'll get a fix for that in on the next version.
> 
> Out of curiosity, what was your date format set to when you saw this?

I'm not sure I follow, haha. Timezone maybe?

```
$ date
Tue Mar 17 10:04:22 CDT 2020
```

**Comment by wren** [comment]
Sorry! I wasn't being very clear. there's a datetime format (`timeformat`) in your jrnl config file (default location: `~/.config/jrnl/jrnl.yaml`). The bug you ran into is in our time parsing file, so I'm hoping to gather some extra data about whether certain formats affect the bug or not. This would help us get a test in place to successfully detect these types of bugs in the future.

**Comment by heydonovan** [comment]
Got it!

```
bash-5.0$ grep 'timeformat' ~/.config/jrnl/jrnl.yaml
timeformat: '%Y-%m-%d %H:%M'
```

**Comment by wren** [comment]
@heydonovan Thank you! We're looking into this.

**Comment by wren** [comment]
@heydonovan Hi! Sorry for not updating this. The related issue (#878) was fixed, so you should be good to go (please let us know if you're not). Thank you!
