### ISSUE TITLE
Exception Occured error after latest update

### ISSUE THREAD

**Issue by mtwb47** [jrnl-org/jrnl#890]
Getting this error when trying to use jrnl. 
Happens with any jrnl --command (including jrnl --version or jrnl -v) or just using jrnl to enter the main mode. 

`Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/lib/python3.8/site-packages), Requirement.parse('tzlocal<2.0,>=1.5'), {'jrnl'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/jrnl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tzlocal<2.0,>=1.5' distribution was not found and is required by jrnl

`

**Comment by micahellison** [comment]
Hi there, could you please provide some information about your environment?

What is your operating system?
How did you download jrnl?
If you didn't use pipx, could you try using pipx to install it?

**Comment by mtwb47** [comment]
Using Arcolinux 
Kernel 5.5.10-arch1-1
I installed from the AUR.

I'll try to use pipx, sure.

**Comment by micahellison** [comment]
There's something wrong (I'm not sure what) with the AUR distribution, which isn't managed here. It looks like they're still working on it: https://aur.archlinux.org/packages/jrnl/

**Comment by mtwb47** [comment]
Pipx worked like a gem. Thanks!!

**Comment by micahellison** [comment]
Glad to help!
