### ISSUE TITLE
Weird output when first installing jrnl on Ubuntu

### ISSUE THREAD

**Issue by aturne13** [jrnl-org/jrnl#891]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`)
jrnl version v2.0.1
  - How you installed Jrnl
pip install jrnl
  - Operating system [MacOS, Linux, Windows?]
Ubuntu 18.04

* **What is the current behavior?**
jrnl works however every time that it opens it outputs the beaut below.
* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
I just install jrnl with pip and it began to spit this out at me.
* **What is the expected behavior?**
ERROR    keyring.backend Error initializing plugin EntryPoint('Windows (alt)', u'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/allan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/allan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape
ERROR    keyring.backend Error initializing plugin EntryPoint('file', u'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/allan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/allan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape
ERROR    keyring.backend Error initializing plugin EntryPoint('pyfs', u'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/allan/.local/lib/python2.7/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/allan/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named escape

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by micahellison** [comment]
Hi there, this issue is most likely because you're running an old version of Python (2.7).

You can use an older version of jrnl (though it won't be compatible with your current jrnl format) by installing 1.9.8:
```
pip install jrnl==1.9.8
```

Or you can upgrade to Python 3.5+ then upgrade jrnl to the latest version (2.3).

**Comment by aturne13** [comment]
Followed the provided advice and choose to download a previous version of jrnl. Everything works just fine now.
