### ISSUE TITLE
Windows tests hang on Travis but not locally

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#962]
A couple tests in core.feature have @skip_win on because they hang in Travis. However, they succeed locally, so there's something different about Travis.

After adding in a bunch of tracers via PR #961, I've narrowed down the freezing line to core.py:358:
```
        if not sys.stdin.isatty():
            # Piping data into jrnl
            raw = sys.stdin.read()
```
It looks like that sys.stdin.isatty() call is true when running behave locally but false in Travis Windows. So in Travis, it runs `raw = sys.stdin.read()` which is causing it to wait until it's finished reading input from the user that doesn't exist. 10 minutes later, the build fails due to timeout.

The idea of this code is to detect whether or not data is being piped into jrnl. Maybe this isn't the best way to check for that, or maybe the behave tests can mock this for the purpose of the test.

**Comment by MinchinWeb** [comment]
I have one test that hangs locally (PowerShell 7 on Windows 10) waiting for a password prompt, here's the output your branch when running the test (I just hit enter twice for the password):

```
  Scenario: Storing a password in Keychain                                        # features/encryption.feature:46
    Given we use the config "multiple.yaml"                                       # features/steps/core.py:73
    When we run "jrnl simple --encrypt" and enter                                 # features/steps/core.py:140
      """
      sabertooth
      sabertooth
      y
      """
run_with_input
cli.run ['simple', '--encrypt']
run
[Configuration updated to newest version at E:\Code\jrnl\features\configs\multiple.yaml]
mode_compose: False, mode_export: True, mode_import: False
journal is open
still going after mode_compose block
Journal encrypted to features/journals/simple.journal.
    When we set the keychain password of "simple" to "sabertooth"                 # features/steps/core.py:203
    Then the config for journal "simple" should have "encrypt" set to "bool:True" # features/steps/core.py:308
    When we run "jrnl simple -n 1"                                                # features/steps/core.py:179
run
mode_compose: False, mode_export: False, mode_import: False
Wrong password, try again.
Password:
Wrong password, try again.
Password:
Extremely wrong password.
    Then the output should contain "2013-06-10 15:40 Life is good"                # features/steps/core.py:250
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      Enter password for new journal:
      Enter password again:
      Do you want to store the password in your keychain? [Y/n]  y
```

I mention it here, because it seems like it might be a similar issue.

**Comment by micahellison** [comment]
Interesting. I'm not able to reproduce that with Powershell 7 on Win 10 on that branch. I ran `poetry run behave` and it got through everything with all tests passed. It's also working fine on the regular Windows command prompt. Any ideas on what might be different in your environment?

**Comment by MinchinWeb** [comment]
To be clear, this isn't a bug introduced by these changes, I just through your changes might make it clearer figuring out why. It's been like this for some time, I just have had the free time to track down why.

This is also 1 of 9 tests that fail for me:
```
Failing scenarios:
  features/delete.feature:2  --delete flag allows deletion of single entry
  features/delete.feature:32  --delete flag with nonsense input deletes nothing (issue #932)
  features/encryption.feature:15  Encrypting a journal
  features/encryption.feature:29  Mistyping your password
  features/encryption.feature:46  Storing a password in Keychain
  features/upgrade.feature:3  Upgrade and parse journals with square brackets
  features/upgrade.feature:14  Upgrading a journal encrypted with jrnl 1.x
  features/upgrade.feature:30  Upgrade and parse journals with little endian date format
  features/upgrade.feature:50  Upgrade with missing encrypted journal
```

No idea what is special about my environment.

Here's more details from the failing tests:
```
  Scenario: --delete flag allows deletion of single entry  # features/delete.feature:2
    Given we use the config "deletion.yaml"                # features/steps/core.py:73
    When we run "jrnl -n 1"                                # features/steps/core.py:179
    Then the output should contain                         # features/steps/core.py:250
      """
      2019-10-29 11:13 Third entry.
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      2019-10-29 11:13 Third entry.

      Captured stderr:
      run
      [Configuration updated to newest version at E:\Code\jrnl\features\configs\deletion.yaml]
      mode_compose: False, mode_export: False, mode_import: False
      journal is open
      still going after mode_compose block

    When we run "jrnl --delete" and enter                  # None
      """
      N
      N
      Y
      """
    When we run "jrnl -n 1"                                # None
    Then the output should contain                         # None
      """
      2019-10-29 11:11 Second entry.
      """


  Scenario: --delete flag with nonsense input deletes nothing (issue #932)  # features/delete.feature:32
    Given we use the config "deletion.yaml"                                 # features/steps/core.py:73
    When we run "jrnl --delete asdfasdf"                                    # features/steps/core.py:179
    When we run "jrnl -n 1"                                                 # features/steps/core.py:179
    Then the output should contain                                          # features/steps/core.py:250
      """
      2019-10-29 11:13 Third entry.
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      2019-10-29 11:13 Third entry.

      Captured stderr:
      run
      [Configuration updated to newest version at E:\Code\jrnl\features\configs\deletion.yaml]
      mode_compose: False, mode_export: True, mode_import: False
      journal is open
      still going after mode_compose block
      No entries deleted, because the search returned no results.
      run
      mode_compose: False, mode_export: False, mode_import: False
      journal is open
      still going after mode_compose block

    And the journal should have 3 entries                                   # None


  Scenario: Encrypting a journal                                                  # features/encryption.feature:15
    Given we use the config "basic.yaml"                                          # features/steps/core.py:73
    When we run "jrnl --encrypt" and enter                                        # features/steps/core.py:140
      """
      swordfish
      swordfish
      n
      """
    Then we should see the message "Journal encrypted"                            # features/steps/core.py:274
    And the config for journal "default" should have "encrypt" set to "bool:True" # features/steps/core.py:308
    When we run "jrnl -n 1" and enter "swordfish"                                 # features/steps/core.py:140
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 163, in run_with_input
          cli.run(args or [])
        File "E:\Code\jrnl\jrnl\cli.py", line 360, in run
          journal = open_journal(journal_name, config)
        File "E:\Code\jrnl\jrnl\Journal.py", line 402, in open_journal
          return EncryptedJournal.EncryptedJournal(name, **config).open()
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 52, in open
          text = self._load(filename)
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 79, in _load
          return util.decrypt_content(keychain=self.name, decrypt_func=decrypt_journal)
        File "E:\Code\jrnl\jrnl\util.py", line 83, in decrypt_content
          password = gp.getpass()
        File "C:\Python38\lib\unittest\mock.py", line 1081, in __call__
          return self._mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1085, in _mock_call
          return self._execute_mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1146, in _execute_mock_call
          result = effect(*args, **kwargs)
        File "features\steps\core.py", line 126, in prompt_return
          return next(inputs)
      StopIteration

      Captured stdout:
      Enter password for new journal:
      Enter password again:
      Do you want to store the password in your keychain? [Y/n]  n
      Password:
      Password:

      Captured stderr:
      run_with_input
      cli.run ['--encrypt']
      run
      mode_compose: False, mode_export: True, mode_import: False
      journal is open
      still going after mode_compose block
      Journal encrypted to features/journals/simple.journal.
      run_with_input
      cli.run ['-n', '1']
      run
      mode_compose: False, mode_export: False, mode_import: False
      Wrong password, try again.

    Then the output should contain "Password"                                     # None
    And the output should contain "2013-06-10 15:40 Life is good"                 # None

  Scenario: Mistyping your password                                               # features/encryption.feature:29
    Given we use the config "basic.yaml"                                          # features/steps/core.py:73
    When we run "jrnl --encrypt" and enter                                        # features/steps/core.py:140
      """
      swordfish
      sordfish
      swordfish
      swordfish
      n
      """
    Then we should see the message "Passwords did not match"                      # features/steps/core.py:274
    And we should see the message "Journal encrypted"                             # features/steps/core.py:274
    And the config for journal "default" should have "encrypt" set to "bool:True" # features/steps/core.py:308
    When we run "jrnl -n 1" and enter "swordfish"                                 # features/steps/core.py:140
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 163, in run_with_input
          cli.run(args or [])
        File "E:\Code\jrnl\jrnl\cli.py", line 360, in run
          journal = open_journal(journal_name, config)
        File "E:\Code\jrnl\jrnl\Journal.py", line 402, in open_journal
          return EncryptedJournal.EncryptedJournal(name, **config).open()
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 52, in open
          text = self._load(filename)
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 79, in _load
          return util.decrypt_content(keychain=self.name, decrypt_func=decrypt_journal)
        File "E:\Code\jrnl\jrnl\util.py", line 83, in decrypt_content
          password = gp.getpass()
        File "C:\Python38\lib\unittest\mock.py", line 1081, in __call__
          return self._mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1085, in _mock_call
          return self._execute_mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1146, in _execute_mock_call
          result = effect(*args, **kwargs)
        File "features\steps\core.py", line 126, in prompt_return
          return next(inputs)
      StopIteration

      Captured stdout:
      Enter password for new journal:
      Enter password again:
      Enter password for new journal:
      Enter password again:
      Do you want to store the password in your keychain? [Y/n]  n
      Password:
      Password:

      Captured stderr:
      run_with_input
      cli.run ['--encrypt']
      run
      mode_compose: False, mode_export: True, mode_import: False
      journal is open
      still going after mode_compose block
      Passwords did not match, please try again
      Journal encrypted to features/journals/simple.journal.
      run_with_input
      cli.run ['-n', '1']
      run
      mode_compose: False, mode_export: False, mode_import: False
      Wrong password, try again.

    Then the output should contain "Password"                                     # None
    And the output should contain "2013-06-10 15:40 Life is good"                 # None

  Scenario: Storing a password in Keychain                                        # features/encryption.feature:46
    Given we use the config "multiple.yaml"                                       # features/steps/core.py:73
    When we run "jrnl simple --encrypt" and enter                                 # features/steps/core.py:140
      """
      sabertooth
      sabertooth
      y
      """
    When we set the keychain password of "simple" to "sabertooth"                 # features/steps/core.py:203
    Then the config for journal "simple" should have "encrypt" set to "bool:True" # features/steps/core.py:308
    When we run "jrnl simple -n 1"                                                # features/steps/core.py:179
Password:
Password:
    Then the output should contain "2013-06-10 15:40 Life is good"                # features/steps/core.py:250
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      Enter password for new journal:
      Enter password again:
      Do you want to store the password in your keychain? [Y/n]  y

      Captured stderr:
      run_with_input
      cli.run ['simple', '--encrypt']
      run
      [Configuration updated to newest version at E:\Code\jrnl\features\configs\multiple.yaml]
      mode_compose: False, mode_export: True, mode_import: False
      journal is open
      still going after mode_compose block
      Journal encrypted to features/journals/simple.journal.
      run
      mode_compose: False, mode_export: False, mode_import: False
      Wrong password, try again.
      Wrong password, try again.
      Extremely wrong password.

Feature: Upgrading Journals from 1.x.x to 2.x.x # features/upgrade.feature:1

  Scenario: Upgrade and parse journals with square brackets  # features/upgrade.feature:3
    Given we use the config "upgrade_from_195.json"          # features/steps/core.py:73
    When we run "jrnl -9" and enter "Y"                      # features/steps/core.py:140
    Then the output should contain                           # features/steps/core.py:250
      """
      2010-06-10 15:00 A life without chocolate is like a bad analogy.

      2013-06-10 15:40 He said "[this] is the best time to be alive".
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      Welcome to jrnl v2.4.2.

      It looks like you've been using an older version of jrnl until now. That's
      okay - jrnl will now upgrade your configuration and journal files. Afterwards
      you can enjoy all of the great new features that come with jrnl 2:

      - Support for storing your journal in multiple files
      - Faster reading and writing for large journals
      - New encryption back-end that makes installing jrnl much easier
      - Tons of bug fixes

      Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
      If you choose to proceed, you will not be able to use your journals with
      older versions of jrnl anymore.

      Continue upgrading jrnl? [y/N]  Y
      2010-06-10 15:00 A life without chocolate is like a bad analogy.

      2013-06-10 15:40 He said "[this] is the best time to be alive".Lorem ipsum dolor
      sit amet, consectetur adipiscing elit.
      | Praesent malesuada
      | quis est ac dignissim. Aliquam dignissim rutrum pretium. Phasellus
      | pellentesque
      | augue et venenatis facilisis.
      |
      |  [2019-08-03 12:55] Some chat log or something
      |
      | Suspendisse potenti. Sed dignissim sed nisl eu consequat. Aenean ante ex,
      | elementum ut interdum et, mattis eget lacus. In commodo nulla nec tellus
      | placerat, sed ultricies metus bibendum. Duis eget venenatis erat. In at dolor
      | dui.

      Captured stderr:
      run_with_input
      cli.run ['-9']
      run

      Following plain text journals will upgraded to jrnl v2.4.2:
          default -> features/journals/simple_jrnl-1-9-5.journal

      Upgrading plain text 'default' journal stored in features/journals/simple_jrnl-1-9-5.journal...
        Created a backup at features/journals/simple_jrnl-1-9-5.journal.backup

      Upgrading config...
        Created a backup at E:\Code\jrnl\features\configs\upgrade_from_195.json.backup

      We're all done here and you can start enjoying jrnl 2.
      [Configuration updated to newest version at E:\Code\jrnl\features\configs\upgrade_from_195.json]
      mode_compose: False, mode_export: False, mode_import: False
      journal is open
      still going after mode_compose block

    Then the journal should have 2 entries                   # None

  Scenario: Upgrading a journal encrypted with jrnl 1.x           # features/upgrade.feature:14
    Given we use the config "encrypted_old.json"                  # features/steps/core.py:73
    When we run "jrnl -n 1" and enter                             # features/steps/core.py:140
      """
      Y
      bad doggie no biscuit
      bad doggie no biscuit
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 163, in run_with_input
          cli.run(args or [])
        File "E:\Code\jrnl\jrnl\cli.py", line 320, in run
          config = install.load_or_install_jrnl()
        File "E:\Code\jrnl\jrnl\install.py", line 100, in load_or_install_jrnl
          upgrade.upgrade_jrnl_if_necessary(config_path)
        File "E:\Code\jrnl\jrnl\upgrade.py", line 133, in upgrade_jrnl_if_necessary
          old_journal = Journal.open_journal(
        File "E:\Code\jrnl\jrnl\Journal.py", line 401, in open_journal
          return EncryptedJournal.LegacyEncryptedJournal(name, **config).open()
        File "E:\Code\jrnl\jrnl\Journal.py", line 82, in open
          text = self._load(filename)
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 132, in _load
          return util.decrypt_content(keychain=self.name, decrypt_func=decrypt_journal)
        File "E:\Code\jrnl\jrnl\util.py", line 83, in decrypt_content
          password = gp.getpass()
        File "C:\Python38\lib\unittest\mock.py", line 1081, in __call__
          return self._mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1085, in _mock_call
          return self._execute_mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1146, in _execute_mock_call
          result = effect(*args, **kwargs)
        File "features\steps\core.py", line 126, in prompt_return
          return next(inputs)
      StopIteration

      Captured stdout:
      Welcome to jrnl v2.4.2.

      It looks like you've been using an older version of jrnl until now. That's
      okay - jrnl will now upgrade your configuration and journal files. Afterwards
      you can enjoy all of the great new features that come with jrnl 2:

      - Support for storing your journal in multiple files
      - Faster reading and writing for large journals
      - New encryption back-end that makes installing jrnl much easier
      - Tons of bug fixes

      Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
      If you choose to proceed, you will not be able to use your journals with
      older versions of jrnl anymore.

      Continue upgrading jrnl? [y/N]  Y
      Password:
      Password:
      Password:

      Captured stderr:
      run_with_input
      cli.run ['-n', '1']
      run

      Following encrypted journals will be upgraded to jrnl v2.4.2:
          default -> features/journals/encrypted_jrnl-1-9-5.journal

      Upgrading encrypted 'default' journal stored in features/journals/encrypted_jrnl-1-9-5.journal...
        Created a backup at features/journals/encrypted_jrnl-1-9-5.journal.backup
      Wrong password, try again.
      Wrong password, try again.

    Then the output should contain "Password"                     # None
    And the output should contain "2013-06-10 15:40 Life is good" # None

  Scenario: Upgrading a config without colors to colors                                                         # features/upgrade.feature:25
    Given we use the config "no_colors.yaml"                                                                    # features/steps/core.py:73
    When we run "jrnl -n 1"                                                                                     # features/steps/core.py:179
    Then the config should have "colors" set to "{'date':'none', 'title':'none', 'body':'none', 'tags':'none'}" # features/steps/core.py:308

  Scenario: Upgrade and parse journals with little endian date format   # features/upgrade.feature:30
    Given we use the config "upgrade_from_195_little_endian_dates.json" # features/steps/core.py:73
    When we run "jrnl -9" and enter "Y"                                 # features/steps/core.py:140
    Then the output should contain                                      # features/steps/core.py:250
      """
      10.06.2010 15:00 A life without chocolate is like a bad analogy.

      10.06.2013 15:40 He said "[this] is the best time to be alive".
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 256, in check_output_inline
          assert text in out or text2 in out, text or text2
      TypeError: 'in <string>' requires string as left operand, not NoneType

      Captured stdout:
      Welcome to jrnl v2.4.2.

      It looks like you've been using an older version of jrnl until now. That's
      okay - jrnl will now upgrade your configuration and journal files. Afterwards
      you can enjoy all of the great new features that come with jrnl 2:

      - Support for storing your journal in multiple files
      - Faster reading and writing for large journals
      - New encryption back-end that makes installing jrnl much easier
      - Tons of bug fixes

      Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
      If you choose to proceed, you will not be able to use your journals with
      older versions of jrnl anymore.

      Continue upgrading jrnl? [y/N]  Y
      10.06.2010 15:00 A life without chocolate is like a bad analogy.

      10.06.2013 15:40 He said "[this] is the best time to be alive".Lorem ipsum dolor
      sit amet, consectetur adipiscing elit.
      | Praesent malesuada
      | quis est ac dignissim. Aliquam dignissim rutrum pretium. Phasellus
      | pellentesque
      | augue et venenatis facilisis.
      |
      |  [03.08.2019 12:55] Some chat log or something
      |
      | Suspendisse potenti. Sed dignissim sed nisl eu consequat. Aenean ante ex,
      | elementum ut interdum et, mattis eget lacus. In commodo nulla nec tellus
      | placerat, sed ultricies metus bibendum. Duis eget venenatis erat. In at dolor
      | dui.

      Captured stderr:
      run_with_input
      cli.run ['-9']
      run

      Following plain text journals will upgraded to jrnl v2.4.2:
          default -> features/journals/simple_jrnl-1-9-5_little_endian_dates.journal

      Upgrading plain text 'default' journal stored in features/journals/simple_jrnl-1-9-5_little_endian_dates.journal...
        Created a backup at features/journals/simple_jrnl-1-9-5_little_endian_dates.journal.backup

      Upgrading config...
        Created a backup at E:\Code\jrnl\features\configs\upgrade_from_195_little_endian_dates.json.backup

      We're all done here and you can start enjoying jrnl 2.
      [Configuration updated to newest version at E:\Code\jrnl\features\configs\upgrade_from_195_little_endian_dates.json]
      mode_compose: False, mode_export: False, mode_import: False
      journal is open
      still going after mode_compose block

    Then the journal should have 2 entries                              # None


  Scenario: Upgrade with missing encrypted journal                                            # features/upgrade.feature:50
    Given we use the config "upgrade_from_195_with_missing_encrypted_journal.json"            # features/steps/core.py:73
    When we run "jrnl -ls" and enter                                                          # features/steps/core.py:140
      """
      Y
      bad doggie no biscuit
      """
      Traceback (most recent call last):
        File "e:\code\jrnl\.venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "e:\code\jrnl\.venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\core.py", line 163, in run_with_input
          cli.run(args or [])
        File "E:\Code\jrnl\jrnl\cli.py", line 320, in run
          config = install.load_or_install_jrnl()
        File "E:\Code\jrnl\jrnl\install.py", line 100, in load_or_install_jrnl
          upgrade.upgrade_jrnl_if_necessary(config_path)
        File "E:\Code\jrnl\jrnl\upgrade.py", line 133, in upgrade_jrnl_if_necessary
          old_journal = Journal.open_journal(
        File "E:\Code\jrnl\jrnl\Journal.py", line 401, in open_journal
          return EncryptedJournal.LegacyEncryptedJournal(name, **config).open()
        File "E:\Code\jrnl\jrnl\Journal.py", line 82, in open
          text = self._load(filename)
        File "E:\Code\jrnl\jrnl\EncryptedJournal.py", line 132, in _load
          return util.decrypt_content(keychain=self.name, decrypt_func=decrypt_journal)
        File "E:\Code\jrnl\jrnl\util.py", line 83, in decrypt_content
          password = gp.getpass()
        File "C:\Python38\lib\unittest\mock.py", line 1081, in __call__
          return self._mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1085, in _mock_call
          return self._execute_mock_call(*args, **kwargs)
        File "C:\Python38\lib\unittest\mock.py", line 1146, in _execute_mock_call
          result = effect(*args, **kwargs)
        File "features\steps\core.py", line 126, in prompt_return
          return next(inputs)
      StopIteration

      Captured stdout:
      Welcome to jrnl v2.4.2.

      It looks like you've been using an older version of jrnl until now. That's
      okay - jrnl will now upgrade your configuration and journal files. Afterwards
      you can enjoy all of the great new features that come with jrnl 2:

      - Support for storing your journal in multiple files
      - Faster reading and writing for large journals
      - New encryption back-end that makes installing jrnl much easier
      - Tons of bug fixes

      Please note that jrnl 1.x is NOT forward compatible with this version of jrnl.
      If you choose to proceed, you will not be able to use your journals with
      older versions of jrnl anymore.


      Error: features/journals/missing.journal does not exist.
      Continue upgrading jrnl? [y/N]  Y
      Password:
      Password:

      Captured stderr:
      run_with_input
      cli.run ['-ls']
      run

      Following encrypted journals will be upgraded to jrnl v2.4.2:
          default -> features/journals/encrypted_jrnl-1-9-5.journal

      Upgrading encrypted 'default' journal stored in features/journals/encrypted_jrnl-1-9-5.journal...
        Created a backup at features/journals/encrypted_jrnl-1-9-5.journal.backup
      Wrong password, try again.

    Then the output should contain "Error: features/journals/missing.journal does not exist." # None
    And the error output should contain "We're all done"                                      # None
    And we should get no error                                                                # None
```

So maybe it's just an issue with mocking user input?

**Comment by micahellison** [comment]
Do you pipe test output to another program, like an IDE? I imagine anything that operates on stdin or stdout might have some side effects.

**Comment by MinchinWeb** [comment]
I'm running this in Windows Terminal, but running it directly into PowerShell does the same thing....

**Comment by wren** [comment]
@MinchinWeb Would you mind walking us through your setup? Do you use poetry? Which version? Which Python version? That sort of stuff.

**Comment by MinchinWeb** [comment]
Sure. Let me know if I miss anything.

- Window 10 Pro, version 10.0.18363 (i.e. "version 1909")
- PowerShell Core 7.0.1, installed globally through Chocolatey
- Windows Terminal 1.0.1401.0, installed via the Windows Store
- Python 3.8.3, installed globally through Chocolatey
- pipx 0.15.3.1, installed via pipx
- poetry 1.0.5, installed via *pipx*
- *jrnl*, installed via `poetry install` in a virutal environment (`.venv') in the root of my jrnl git checkout folder
- behave 1.2.6, installed with jrnl in the virtual environment
- tests run through calling *behave* directly from the root jrnl git checkout folder, with the virtual environment active (but the results seem to be the same if I call behave through poetry, via `poetry run behave`)

The results are the same if I run the tests directly on PowerShell 5.1.18362.752 or on CMD.

This is what is installed in the virtual environment:

```
(.venv) <user>@<computer> E:\Code\jrnl [2.4-dayone-fixes ≡ +2 ~0 -0 !]                                         10:09 AM
λ pip list
Package         Version  Location
--------------- -------- ------------
ansiwrap        0.8.4
appdirs         1.4.3
asteval         0.9.18
attrs           19.3.0
behave          1.2.6
black           19.10b0
cffi            1.14.0
click           7.1.2
colorama        0.4.3
cryptography    2.9.2
future          0.18.2
Jinja2          2.11.2
joblib          0.14.1
jrnl            2.4.2    e:\code\jrnl
keyring         21.2.1
livereload      2.6.1
lunr            0.5.6
Markdown        3.2.1
MarkupSafe      1.1.1
mkdocs          1.1
nltk            3.5
parse           1.15.0
parse-type      0.5.2
parsedatetime   2.5
passlib         1.7.2
pathspec        0.8.0
pip             20.1.1
ptvsd           4.3.2
pycparser       2.20
pyflakes        2.2.0
python-dateutil 2.8.1
pytz            2020.1
pywin32-ctypes  0.2.0
pyxdg           0.26
PyYAML          5.3.1
regex           2020.4.4
setuptools      41.2.0
six             1.14.0
textwrap3       0.9.2
toml            0.10.0
tornado         6.0.4
tqdm            4.46.0
typed-ast       1.4.1
tzlocal         2.0.0
```

**Comment by MinchinWeb** [comment]
Travis runs it's tests on Windows 1809. Don't know if that would make the difference...

**Comment by micahellison** [comment]
Our environments are extremely similar. I think you might be running into the pesky Windows line ending issues. I was able to reproduce the stuck password prompt by changing my `core.autocrlf` configuration.

We can solve it by changing your global git configuration, but it would be nice to reduce the number of special instructions required for Windows devs, and besides, it feels a little rude to tell people what their globals should be! I think we can handle this in the repo's git configuration.

Could you try pulling the [tests-line-endings](https://github.com/micahellison/jrnl/tree/tests-line-endings) branch from my fork then running the following from the jrnl directory to ensure the line endings are set:
```
del features\* /q /s
git reset --hard
```

**Comment by MinchinWeb** [comment]
I guess line endings is the issue, although I don't understand the mechanism in this case. In any case, good catch.

On your `test-line-endings` branch:

```
13 features passed, 0 failed, 1 skipped
98 scenarios passed, 0 failed, 5 skipped
477 steps passed, 0 failed, 22 skipped, 0 undefined
Took 0m3.447s
```

**Comment by micahellison** [comment]
Awesome, thanks for testing!

The reason for the problem is that the default/recommended settings for most Windows git installations cause all line endings to be converted into CRLF when you check out. There must be something in the tests where an LF is inserted but if the test has a line ending with CRLF, the test hangs while waiting for that CR.

I've gotten around this by setting the autocrlf setting to false locally and in Travis (#823), but a much more consistent solution is to ensure that all test data is always checked out with LF line endings.

**Comment by wren** [comment]
Aha! Thanks to @micahellison's notes above, I am able to get the test to fail locally with `echo | behave`. I'm guessing Travis is piping to behave on Windows, but never actually sends any input for to be read (which we can also simulate with something like `sleep 999 | behave`). We can sidestep this with a mock (as mentioned above).

I'll have a PR shortly, and we'll see if the tests pass!

**Comment by wren** [comment]
🎉 Tests passed! 🎉
